version: '3'
services:
    web:
        image: nginx:1.25.2-alpine3.18
        ports:
            - "8930:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app:/app
        restart: always
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
        restart: always
    db:
        image: mariadb:11.1.2-jammy
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'formdb'
        volumes:
            - formdb:/var/lib/mysql
        ports:
            - "33930:3306"
        restart: always
volumes:
    formdb: {}